kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "crushftp.fullname" . }}
  labels:
    {{- include "crushftp.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.configVolume.accessMode }}
  {{- if .Values.shared.storageClassName }}
  storageClassName: {{ .Values.shared.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.configVolume.size }}
